services:
    est_idcard.reader:
        class: TFox\EstIdcardBundle\Service\CertificateReaderService

    est_id_card.security.authentication.provider:
        class:  TFox\EstIdcardBundle\Security\Authentication\Provider\EstIdcardAuthenticationProvider
        arguments: ["", "%kernel.cache_dir%/security/nonces"]

    est_id_card.security.authentication.listener:
        class:  TFox\EstIdcardBundle\Security\Firewall\EstIdcardListener
        arguments: ["@security.context", "@router", "@session", "@security.authentication.manager", "@est_idcard.reader", "login_path", "login_check_path"]
        
    est_id_card.security.user.provider:
        class:  TFox\EstIdcardBundle\Security\User\EstIdcardUserProvider
        arguments: [ "@session" ]